site_name: Online Judges
theme:
  name: material
markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
